### ISSUE TITLE
Parse setup

### ISSUE THREAD

**Issue by deonna** [accountabilibuddies/accountabilibuddies#2]
Set up Parse so we can use it in our app. Use Gmail account from Slack group so we can all access account details.

**Comment by amodsamant** [comment]
Commit: 4863d8d934f640dc987d5cc3e16c05f1675492ee

**Comment by amodsamant** [comment]
Added https://github.com/accountabilibuddies/parse-server-example and connected Heroku server to this github link to deploy server code.
