### ISSUE TITLE
User can add contacts from Facebook friends list

### ISSUE THREAD

**Issue by deonna** [accountabilibuddies/accountabilibuddies#8]

**Comment by deonna** [comment]
@amodsamant and @divyayadav1606 - please comment.

Should we be accessing:

**1) the list of friends who are already using the app (i.e., have already authorized the app)**

OR 

**2) the list of all friends of the current user?**

2) more complicated and will involve a Graph API call.

Right now, we don't have any user stories that involve the user inviting friends to join our app, so I am leaning towards 1).

Relevant user story for 1): 

`After logging in for the first time, user gets the option to add friends who are already using the app`

**Comment by divyayadav1606** [comment]
I would say option 2, that ways we get to invite users as well ?? if its too much we can keep it as stretch as it wont count success of demo IMHO

**Comment by deonna** [comment]
Thanks @divyayadav1606 - I think adding invites may have to go into stretch. I think 1) will be fine for the purpose of getting the app functional.
